/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rene.view;

import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;

/**
 *
 * @author Rene_sever
 */
public class ContaPagarView extends javax.swing.JInternalFrame {
    
     //Botões da barra de tarrefa
    private JButton jBNovo;
    private JButton jBFormaPGTO;
    private JButton jBSalvar;
    private JButton jBCancelar;
    private JButton jBExcluir;
    private JButton jBFormasPGTO;
    private JSeparator jSeparador1;
    private JSeparator jSeparador2;
    private JSeparator jSeparador3;
    private JSeparator jSeparador4;
    
      private static ContaPagarView contaPagarView;
    
     public static ContaPagarView getIntancia() {
        if (contaPagarView == null) {
            contaPagarView = new ContaPagarView();
            contaPagarView.setVisible(true);
        }
        return contaPagarView;
    }
    /**
     * Creates new form ConstaPagar
     */
    public ContaPagarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLNomeFornecedor = new javax.swing.JLabel();
        jTBFerramentas = new javax.swing.JToolBar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Contas á Pagar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("N°. Documento:");

        jTextField2.setToolTipText("");
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Data Lancamento:");

        jLabel3.setText("Fornecedor:");

        jButton1.setText("...");

        jLNomeFornecedor.setText("Nome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jButton1)
                        .addComponent(jLNomeFornecedor))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //Inicializando botões do TollBar
        jBNovo = new JButton();
        jBNovo.setVisible(false);
        jBFormaPGTO = new JButton();
        jBFormaPGTO.setVisible(false);
        jBSalvar = new JButton();
        jBSalvar.setVisible(false);
        jBCancelar = new JButton();
        jBCancelar.setVisible(false);
        jBExcluir = new JButton();
        jBExcluir.setVisible(false);

        jSeparador2 = new JSeparator();
        jSeparador2.setVisible(false);
        jSeparador3 = new JSeparator();
        jSeparador3.setVisible(false);
        jSeparador4 = new JSeparator();
        jSeparador4.setVisible(false);

        jSeparador2.setPreferredSize(new java.awt.Dimension(10, 0));
        jSeparador3.setPreferredSize(new java.awt.Dimension(10, 0));
        jSeparador4.setPreferredSize(new java.awt.Dimension(10, 0));

        ImageIcon img1 = new javax.swing.ImageIcon(getClass().getResource("/br/com/rene/view/imagem/Novo.png"));
        img1.setImage(img1.getImage().getScaledInstance(40, 40, 100));
        jBNovo.setIcon(img1);
        jBNovo.setVisible(false);
        jBNovo.setToolTipText("Novo");
        jBNovo.addActionListener((ActionEvent evt) -> {
            novo();
            HabilitaDesabilitaBatao(false);
        });
        ImageIcon img2 = new javax.swing.ImageIcon(getClass().getResource("/br/com/rene/view/imagem/Cancelar.png"));
        img2.setImage(img2.getImage().getScaledInstance(40, 40, 100));
        jBCancelar.setIcon(img2);
        jBCancelar.setVisible(false);
        jBCancelar.setToolTipText("Cancelar");
        jBCancelar.addActionListener((ActionEvent evt) -> {
            cancelar();
            HabilitaDesabilitaBatao(true);
        });
        ImageIcon img3 = new javax.swing.ImageIcon(getClass().getResource("/br/com/rene/view/imagem/Excluir.png"));
        img3.setImage(img3.getImage().getScaledInstance(40, 40, 100));
        jBExcluir.setIcon(img3);
        jBExcluir.setVisible(false);
        jBExcluir.setToolTipText("Excluir");
        jBExcluir.addActionListener((ActionEvent evt) -> {
            excluir();
            HabilitaDesabilitaBatao(true);
        });
        ImageIcon img4 = new javax.swing.ImageIcon(getClass().getResource("/br/com/rene/view/imagem/Localizar.png"));
        img4.setImage(img4.getImage().getScaledInstance(40, 40, 100));
        jBFormaPGTO.setIcon(img4);
        jBFormaPGTO.setVisible(false);
        jBFormaPGTO.setText("Formas PGTO");
        jBFormaPGTO.setToolTipText("Formas de Pagamentos");
        jBFormaPGTO.addActionListener((ActionEvent evt) -> {
            FormaPGTO();
        });
        ImageIcon img5 = new javax.swing.ImageIcon(getClass().getResource("/br/com/rene/view/imagem/Salvar.png"));
        img5.setImage(img5.getImage().getScaledInstance(40, 40, 100));
        jBSalvar.setIcon(img5);
        jBSalvar.setVisible(false);
        jBSalvar.setToolTipText("Salvar");
        jBSalvar.addActionListener((ActionEvent evt) -> {
            salvar();
            HabilitaDesabilitaBatao(true);
        });
        montaTBFerramentas();
        HabilitaDesabilitaBatao(true);
        jTBFerramentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTBFerramentas.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTBFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTBFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1006, 577);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLNomeFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jTBFerramentas;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

public void salvar() {
     
    }

    public void cancelar() {
       
    }

    public void novo() {
         // itemControl.novo();
    }

    public void excluir() {
         if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
         //   try {
               // itemControl.excluir();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
         //   } catch (RemoteException e) {
           //     JOptionPane.showMessageDialog(null, e.getMessage(), "Falha de red", JOptionPane.ERROR_MESSAGE);
          // }
        }
    }

    public void FormaPGTO() {
        PesquisaView pesquisa;
     //   pesquisa = new PesquisaView(cadItemView, true, item);
      //  pesquisa.setVisible(true);
    }
    
       private void montaTBFerramentas() {
        jTBFerramentas.add(jBNovo);
        jTBFerramentas.add(jSeparador2);
        jTBFerramentas.add(jBExcluir);
        jTBFerramentas.add(jSeparador3);
        jTBFerramentas.add(jBFormaPGTO);
        jTBFerramentas.add(jBSalvar);
        jTBFerramentas.add(jSeparador4);
        jTBFerramentas.add(jBCancelar);
    }

    private void HabilitaDesabilitaBatao(boolean habilitar) {
        jBNovo.setVisible(habilitar);
        jBSalvar.setVisible(!habilitar);
        jBCancelar.setVisible(!habilitar);
        jBExcluir.setVisible(habilitar);
        jBFormaPGTO.setVisible(habilitar);
        jSeparador2.setVisible(habilitar);
        jSeparador3.setVisible(habilitar);
        jSeparador4.setVisible(!habilitar);
        jTBFerramentas.repaint();
    }

    public void DesabilitaTodosBatao() {
        jBNovo.setVisible(false);
        jBCancelar.setVisible(false);
        jBExcluir.setVisible(false);
        jBFormaPGTO.setVisible(false);
        jBSalvar.setVisible(false);
        jSeparador2.setVisible(false);
        jSeparador3.setVisible(false);
        jSeparador4.setVisible(false);
        jTBFerramentas.repaint();
        jTBFerramentas.revalidate();
        
       
    }

}
